services:
  iptv-sources:
    image: cs3306/iptv-sources:latest
    container_name: iptv-sources
    volumes:
      - ./data:/app/data
      - ./config.json:/app/config.json
    environment:
      - TZ=Asia/Shanghai
    restart: "no"
